name: fsdl-text-recognizer-2021
channels:
  - defaults
dependencies:
  - python=3.7  # Updated since google colab now uses python 3.7
  - cudatoolkit=10.1
  - cudnn=7.6
  - pip
  - pip:
    - pip-tools
